language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
sudo: false
env:
  global:
    - "AUTHORIZE_LIVE_TESTS=1"
before_install: "pip install codecov"
install: "pip install -r requirements.txt"
script: "coverage run tests/run_tests.py"
after_success: codecov
